# Site settings
title: Marcin Kraszewski
email: your-email@example.com
description: >-
  Personal portfolio showcasing my projects and professional skills.
baseurl: ""
url: "https://yourusername.github.io"
github_username: yourusername
linkedin_username: marcin-kraszewski

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Collections
collections:
  projects:
    output: true
    permalink: /projects/:path/

# Defaults
defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "project"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"
